---
- name: Stop Zabbix Agent
  systemd:
    name: zabbix-agent
    state: stopped

- name: Stop Zabbix Proxy
  systemd:
    name: zabbix-proxy
    state: stopped

- name: Find file dbsqlite
  shell: cat /etc/zabbix/zabbix_proxy.conf | grep ^DBName | cut -d= -f2
  register: path
  when: zabbix_proxy_database == 'sqlite3'

- debug: 
    msg: "{{ path.stdout }}"
  when: zabbix_proxy_database == 'sqlite3'

- name: Remove file (delete file)
  file:
    path: "{{ path.stdout }}"
    state: absent
  when: zabbix_proxy_database == 'sqlite3'
  
- name: "Debian | Set facts for Zabbix <= 5.0"
  set_fact:
    datafiles_path: "/usr/share/doc/zabbix-proxy-{{ zabbix_proxy_database }}"
  when:
    - zabbix_version is version_compare('5.0', '<=')

- name: "Debian | Set facts for Zabbix >= 5.4"
  set_fact:
    datafiles_path: "/usr/share/doc/zabbix-sql-scripts/{{ zabbix_proxy_database }}"
  when:
    - zabbix_version is version_compare('5.4', '>=')

- name: Add an Apt signing key zabbix
  apt_key:
    url: http://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Install repo zabbix
  apt_repository:
    repo: "{{ item }} https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu {{ ansible_distribution_release }} main"
    state: present
  when: 
   - zabbix_repo == "zabbix"
   - ansible_distribution == "Ubuntu"
  with_items:
    - deb-src
    - deb

- name: Install repo zabbix
  apt_repository:
    repo: "{{ item }} https://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian {{ ansible_distribution_release }} main"
    state: present
  when: 
   - zabbix_repo == "zabbix"
   - ansible_distribution == "Debian"
  with_items:
    - deb-src
    - deb

- name: Update Zabbix packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - zabbix-proxy-{{ zabbix_proxy_database }}
    - zabbix-agent
  when: zabbix_version is version_compare('5.0', '==')

- name: Update Zabbix packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - zabbix-proxy-{{ zabbix_proxy_database }}
    - zabbix-agent
    - zabbix-sql-scripts
  when: zabbix_version is version_compare('5.4', '>=')

- name: Make sure zabbix-agent service is running
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes
