---
- name: Stop Zabbix Agent
  systemd:
    name: zabbix-agent
    state: stopped

- name: Stop Zabbix Proxy
  systemd:
    name: zabbix-proxy
    state: stopped

- name: Find file dbsqlite
  shell: find / -name *proxy.db
  register: path

- debug: 
    msg: "{{ path.stdout }}"

- name: Remove file
  shell: rm -rf "{{ path.stdout }}"
  ignore_errors: true
  
- name: "Debian | Set facts for Zabbix <= 5.0"
  set_fact:
    datafiles_path: "/usr/share/doc/zabbix-proxy-{{ zabbix_proxy_database }}"
  when:
    - zabbix_version is version_compare('5.0', '<=')

- name: "Debian | Set facts for Zabbix >= 5.4"
  set_fact:
    datafiles_path: "/usr/share/doc/zabbix-sql-scripts/{{ zabbix_proxy_database }}"
  when:
    - zabbix_version is version_compare('5.4', '>=')

- name: Only run update
  apt:
    update_cache: yes
    upgrade: yes

- name: Add an Apt signing key zabbix
  apt_key:
    url: http://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Install repo zabbix
  apt_repository:
    repo: "{{ item }} https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu {{ ansible_distribution_release }} main"
    state: present
  when: zabbix_repo == "zabbix"
  with_items:
    - deb-src
    - deb

- name: Install packages dependencies
  apt:
    name:
        - net-tools
        - vim
        - nano
        - wget
        - telnet
        - rsync
        - git
        - python3
        - python3-pip
    state: present

- name: Update Zabbix packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - zabbix-proxy-{{ zabbix_proxy_database }}
    - zabbix-agent
  when: zabbix_version <= 5.0

- name: Update Zabbix packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - zabbix-proxy-{{ zabbix_proxy_database }}
    - zabbix-agent
  when: zabbix_version >= 5.4

- name: Install zabbix-scripts >= 5.4
  apt:
    name: zabbix-sql-scripts
    state: present
  when: zabbix_version >= 5.4

- name: Make sure zabbix-agent service is running
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes

- name: Copy zabbix_proxy.conf template 
  template:
    src: zabbix_proxy.conf.j2
    dest: /etc/zabbix/zabbix_proxy.conf

- name: Copy zabbix_agent.conf template 
  template:
    src: zabbix_agentd.conf.44.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent