---
- name: Stop zabbix-agent
  systemd:
    name: zabbix-agent
    state: stopped

- name: Stop zabbix-proxy
  systemd:
    name: zabbix-proxy
    state: stopped

- name: Find file dbsqlite
  shell: find / -name *proxy.db
  register: path

- debug: 
    msg: "{{ path.stdout }}"

- name: Remove file
  shell: rm -rf "{{ path.stdout }}"
  ignore_errors: true

- name: "RedHat | Set facts for Zabbix <= 5.0"
  set_fact:
    datafiles_path: "/usr/share/doc/zabbix-proxy-{{ zabbix_proxy_database }}*"
  when:
    - zabbix_version is version_compare('5.0', '<=')
    - ansible_distribution_major_version == '7'
  tags:
    - zabbix-proxy
  
- name: "RedHat | Set facts for Zabbix <= 5.0"
  set_fact:
    datafiles_path: "/usr/share/doc/zabbix-proxy-{{ zabbix_proxy_database }}"
  when:
    - zabbix_version is version_compare('5.0', '<=')
    - ansible_distribution_major_version == '8'
  tags:
    - zabbix-proxy
  
- name: "RedHat | Set facts for Zabbix >= 5.4"
  set_fact:
    datafiles_path: "/usr/share/doc/zabbix-sql-scripts/{{ zabbix_proxy_database }}"
  when:
    - zabbix_version is version_compare('5.4', '>=')
  tags:
    - zabbix-proxy
    
- name: Remove repository (and clean up left-over metadata)
  yum_repository:
    name: zabbix-repo
    state: absent
  notify: yum-clean-metadata

- name: Install Zabbix Repo.
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"

- name: Update Zabbix packages
  yum:
    name: "{{ item }}"
    state: latest
    update_only: yes
  with_items:
    - zabbix-proxy-{{ zabbix_proxy_database }}
    - zabbix-agent
  when: zabbix_version <= 5.0

- name: Update Zabbix packages
  yum:
    name: "{{ item }}"
    state: latest
    update_only: yes
  with_items:
    - zabbix-proxy-{{ zabbix_proxy_database }}
    - zabbix-agent
  when: zabbix_version >= 5.4

- name: Install zabbix-scripts >= 5.4
  yum:
    name: zabbix-sql-scripts
    state: present
  when: zabbix_version >= 5.4

- name: Copy zabbix_proxy.conf template
  template:
    src: zabbix_proxy.conf.j2
    dest: /etc/zabbix/zabbix_proxy.conf

- name: Restart zabbix-agent
  systemd:
    name: zabbix-agent
    state: restarted