- name: "Sqlite3 | Default Database Path"
  set_fact:
    zabbix_proxy_dbname: /var/lib/zabbix/zabbix_proxy.db
  when:
    - zabbix_proxy_dbname == "zabbix_proxy"

- name: Create a directory if it does not exist
  file:
    path: "{{ zabbix_proxy_dbname | dirname }}"
    owner: zabbix
    group: zabbix
    state: directory
    mode: '0755'
  when:
    - zabbix_database_creation
    
- name: "Get the file for schema.sql"
  shell: ls -1 {{ datafiles_path }}/schema.sql.gz
  changed_when: False
  when:
    - zabbix_database_sqlload
  register: ls_output_create

- name: Import database Zabbix-proxy
  shell: |
   zcat {{ ls_output_create.stdout }} | sqlite3 {{ zabbix_proxy_dbname }}
   chown -R zabbix:zabbix /var/lib/zabbix/zabbix_proxy.db
  when:
    - zabbix_database_creation